name: Generate Snake

on:
  schedule: # Executa a cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install pip dependencies
        run: |
          pip install requests
      
      - name: Generate Snake
        run: |
          curl -o output/github-contribution-grid-snake.svg "https://github.com/BrenoLemesD/BrenoLemesD/blob/output/github-contribution-grid-snake.svg"
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generated snake grid"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
